export const lorem = [
	`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et malesuada fames ac turpis egestas sed tempus. In vitae turpis massa sed elementum tempus egestas sed sed. Vitae congue eu consequat ac felis. Iaculis nunc sed augue lacus viverra vitae congue eu consequat. Non quam lacus suspendisse faucibus. Faucibus et molestie ac feugiat. Porta nibh venenatis cras sed felis eget velit. Luctus accumsan tortor posuere ac ut consequat semper viverra nam. Tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Scelerisque varius morbi enim nunc faucibus a. Neque vitae tempus quam pellentesque nec nam. Eget sit amet tellus cras adipiscing enim eu. Nibh tortor id aliquet lectus proin nibh nisl. Non quam lacus suspendisse faucibus. Malesuada fames ac turpis egestas sed tempus urna et pharetra. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Egestas sed sed risus pretium quam. Vulputate dignissim suspendisse in est ante in nibh mauris cursus. Id nibh tortor id aliquet.

  Eu non diam phasellus vestibulum lorem sed risus ultricies. Lorem sed risus ultricies tristique nulla aliquet enim. Et netus et malesuada fames ac turpis. Lorem ipsum dolor sit amet consectetur. Augue lacus viverra vitae congue eu. Risus sed vulputate odio ut enim blandit volutpat maecenas volutpat. Etiam tempor orci eu lobortis. Sed felis eget velit aliquet sagittis. Vel fringilla est ullamcorper eget nulla facilisi. Egestas pretium aenean pharetra magna ac. In ornare quam viverra orci. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Justo nec ultrices dui sapien eget mi proin sed libero. At elementum eu facilisis sed odio morbi. Sed elementum tempus egestas sed sed.

  Luctus accumsan tortor posuere ac ut. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Nisl purus in mollis nunc sed id. Dignissim enim sit amet venenatis urna cursus eget nunc. Mauris augue neque gravida in fermentum. Quis enim lobortis scelerisque fermentum dui faucibus in ornare quam. Orci dapibus ultrices in iaculis nunc sed augue lacus. Id semper risus in hendrerit gravida rutrum. Amet consectetur adipiscing elit ut aliquam. Fames ac turpis egestas integer eget aliquet. Proin fermentum leo vel orci porta non pulvinar. Eget magna fermentum iaculis eu non diam phasellus vestibulum. Nulla pharetra diam sit amet nisl suscipit adipiscing. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Ac ut consequat semper viverra nam. Magna etiam tempor orci eu lobortis elementum nibh tellus. Proin sagittis nisl rhoncus mattis rhoncus urna neque. Mauris in aliquam sem fringilla ut morbi tincidunt. Accumsan lacus vel facilisis volutpat est velit.

  Eu facilisis sed odio morbi. Sed arcu non odio euismod lacinia at quis risus. Bibendum est ultricies integer quis auctor elit sed vulputate. Orci porta non pulvinar neque laoreet suspendisse. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Nisl condimentum id venenatis a condimentum vitae. Commodo ullamcorper a lacus vestibulum sed arcu non odio euismod. Fringilla urna porttitor rhoncus dolor. Venenatis cras sed felis eget velit aliquet sagittis id consectetur. Consectetur libero id faucibus nisl tincidunt eget nullam non nisi. Nunc sed blandit libero volutpat sed. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Fringilla est ullamcorper eget nulla facilisi. Quam nulla porttitor massa id neque aliquam vestibulum morbi.

  Lectus proin nibh nisl condimentum id venenatis. Mauris augue neque gravida in. Turpis egestas maecenas pharetra convallis posuere morbi. Proin sagittis nisl rhoncus mattis. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus et. Amet mattis vulputate enim nulla aliquet. Est ante in nibh mauris cursus mattis. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est velit. Tellus cras adipiscing enim eu turpis egestas.`,
];
